name: Java CI with Maven
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
 
      - name: Unit test
        run: |
          cd ./
          eval mvn test
          
      - name: Run CodeScene Analysis
        run: |
          docker run \
            -v /github/workspace:/app \
            codescene-analysis:latest \
            analyze --config codescene.yaml --token S_NYpqdEUimo6yice90UhGYt4NmOr4CvxZ2fULoFUpk.C3oeAHoGjisKbrzBzbG3pZve1aXZkDBRQafvftjpYqE
            
      - name: Build Docker image
        run: |
          docker build -t codescene-analysis .
          docker tag codescene-analysis keerthikolati/codescene-analysis:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: keerthikolati
          password: dckr_pat_WNAC2pxJKswhxkJ-Pm1sDgPH4U0
      - name: Push Docker image to registry
        run: docker push codescene-analysis:latest
