name: Java CI with Maven and CodeScene
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Build with Maven
        run: mvn -B package --file pom.xml
 
      - name: Build Docker image
        run: |
          docker build -t keerthikolati/codescene-analysis:latest .
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: keerthikolati
          password: dckr_pat_WNAC2pxJKswhxkJ-Pm1sDgPH4U0
 
      - name: Push Docker image to registry
        run: docker push keerthikolati/codescene-analysis:latest
 
      - name: Run CodeScene Analysis
        run: |
          docker run \
            -v ${{ github.workspace }}/src:/app/src \
            -v ${{ github.workspace }}/codescene.yaml:/app/codescene.yaml \
            -e CODESCENE_API_TOKEN=S_NYpqdEUimo6yice90UhGYt4NmOr4CvxZ2fULoFUpk.C3oeAHoGjisKbrzBzbG3pZve1aXZkDBRQafvftjpYqE \
            keerthikolati/codescene-analysis:latest \
            analyze --config /app/codescene.yaml
 
        env:
          CODESCENE_API_TOKEN: S_NYpqdEUimo6yice90UhGYt4NmOr4CvxZ2fULoFUpk.C3oeAHoGjisKbrzBzbG3pZve1aXZkDBRQafvftjpYqE
